require('settings')
require('mappings')
require('colorschemes-config.sonokai')
require('packer-config')
require('lualine-config')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
